In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv('original.csv')

In [4]:
data.head(10)

clientid        income        age         loan  default
0         1  66155.925095  59.017015  8106.532131        0
1         2  34415.153966  48.117153  6564.745018        0
2         3  57317.170063  63.108049  8020.953296        0
3         4  42709.534201  45.751972  6103.642260        0
4         5  66952.688845  18.584336  8770.099235        1
5         6  24904.064140  57.471607    15.498598        0
6         7  48430.359613  26.809132  5722.581981        0
7         8  24500.141984  32.897548  2971.003310        1
8         9  40654.892537  55.496853  4755.825280        0
9        10  25075.872771  39.776378  1409.230371        0

In [5]:
data.tail(10)

clientid        income        age         loan  default
1990      1991  34237.575419  34.101654  2658.090632        0
1991      1992  26300.446554  45.539385  2317.393678        0
1992      1993  30803.806165  23.250084   623.024153        0
1993      1994  54421.410155  26.821928  3273.631823        0
1994      1995  24254.700791  37.751622  2225.284643        0
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

In [6]:
data.shape

(2000, 5)

In [7]:
data.describe()

clientid        income          age          loan      default
count  2000.000000   2000.000000  1997.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018    40.807559   4444.369695     0.141500
std     577.494589  14326.327119    13.624469   3045.410024     0.348624
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     500.750000  32796.459717    28.990415   1939.708847     0.000000
50%    1000.500000  45789.117313    41.317159   3974.719419     0.000000
75%    1500.250000  57791.281668    52.587040   6432.410625     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

In [8]:
data.default.value_counts()

0    1717
1     283
Name: default, dtype: int64

In [9]:
x=data.drop(columns=['default','clientid'],axis=1)

In [10]:
y=data.iloc[:,-1]

In [11]:
x

income        age         loan
0     66155.925095  59.017015  8106.532131
1     34415.153966  48.117153  6564.745018
2     57317.170063  63.108049  8020.953296
3     42709.534201  45.751972  6103.642260
4     66952.688845  18.584336  8770.099235
...            ...        ...          ...
1995  59221.044874  48.518179  1926.729397
1996  69516.127573  23.162104  3503.176156
1997  44311.449262  28.017167  5522.786693
1998  43756.056605  63.971796  1622.722598
1999  69436.579552  56.152617  7378.833599

[2000 rows x 3 columns]

In [12]:
y

0       0
1       0
2       0
3       0
4       1
       ..
1995    0
1996    0
1997    1
1998    0
1999    0
Name: default, Length: 2000, dtype: int64

In [13]:
x.isnull().sum()

income    0
age       3
loan      0
dtype: int64

In [14]:
x['age'].fillna(x['age'].mean(),inplace=True)

In [15]:
x.isnull().sum()

income    0
age       0
loan      0
dtype: int64

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
dtree=DecisionTreeClassifier()

In [18]:
dtree.fit(x,y)

DecisionTreeClassifier()

In [19]:
y.value_counts()

0    1717
1     283
Name: default, dtype: int64

## Under sampling

In [20]:
from imblearn import under_sampling

In [21]:
u_s = under_sampling.RandomUnderSampler()

In [22]:
x_res,y_res=u_s.fit_resample(x,y)

In [23]:
x_res.shape, y_res.shape

((566, 3), (566,))

In [24]:
y_res.value_counts()

0    283
1    283
Name: default, dtype: int64

In [25]:
under_pred=dtree.predict(x_res)

In [26]:
under_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [28]:
accuracy_score(y_res,under_pred)

1.0

In [29]:
confusion_matrix(y_res,under_pred)

array([[283,   0],
       [  0, 283]])

## Over sampling

In [30]:
from imblearn import under_sampling,over_sampling

In [31]:
o_s=over_sampling.RandomOverSampler()

In [32]:
y.value_counts()

0    1717
1     283
Name: default, dtype: int64

In [33]:
x_o,y_o = o_s.fit_resample(x,y)

In [34]:
x_o.shape,y_o.shape

((3434, 3), (3434,))

In [35]:
y_o.value_counts()

0    1717
1    1717
Name: default, dtype: int64

In [36]:
dtree.fit(x_o,y_o)

DecisionTreeClassifier()

In [37]:
o_pred=dtree.predict(x_o)

In [38]:
accuracy_score(y_o,o_pred)

1.0

In [39]:
confusion_matrix(y_o,o_pred)

array([[1717,    0],
       [   0, 1717]])

## Ensemble sampling

In [40]:
from imblearn import ensemble

In [41]:
e_s=ensemble.BalancedRandomForestClassifier()

In [42]:
e_s.fit(x,y)

BalancedRandomForestClassifier()

In [43]:
e_pred=e_s.predict(x)

In [44]:
accuracy_score(y,e_pred)

0.974

In [45]:
confusion_matrix(y,e_pred)

array([[1665,   52],
       [   0,  283]])

## SMOTE

In [46]:
from imblearn.combine import SMOTETomek

In [47]:
# By default it samples 50%, if we want to give custom input then give it in the braket
smote=SMOTETomek(0.90)
# here the 90% of the data is considered for the sampling

/home/hari/.local/lib/python3.10/site-packages/imblearn/utils/_validation.py:586: FutureWarning: Pass sampling_strategy=0.9 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [48]:
y.value_counts()

0    1717
1     283
Name: default, dtype: int64

In [49]:
x_s,y_s=smote.fit_resample(x,y)

In [50]:
x_s.shape, y_s.shape

((3078, 3), (3078,))

In [51]:
y_s.value_counts()

0    1625
1    1453
Name: default, dtype: int64

In [52]:
dtree.fit(x_s,y_s)

DecisionTreeClassifier()

In [53]:
s_pred=dtree.predict(x_s)

In [54]:
accuracy_score(y_s,s_pred)

1.0

In [55]:
confusion_matrix(y_s,s_pred)

array([[1625,    0],
       [   0, 1453]])

## Hyperparameter tuning

### grid search CV

In [56]:
from sklearn.model_selection import GridSearchCV

In [57]:
from sklearn.ensemble import RandomForestClassifier

In [58]:
rdt_model=RandomForestClassifier()

In [59]:
parameters = {'max_depth':[5,10,15,20,30],
             'random_state':[0,1,2,3,4],
             'n_estimators':[10,30,50,70,100,150]}

In [60]:
grid=GridSearchCV(rdt_model,parameters,cv=5)

In [61]:
grid.fit(x,y)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [5, 10, 15, 20, 30],
                         'n_estimators': [10, 30, 50, 70, 100, 150],
                         'random_state': [0, 1, 2, 3, 4]})

In [62]:
grid.best_params_

{'max_depth': 10, 'n_estimators': 50, 'random_state': 0}

In [63]:
grid.best_score_

0.9884999999999999

### Random search CV

In [64]:
from sklearn.model_selection import RandomizedSearchCV

In [65]:
random=RandomizedSearchCV(rdt_model,parameters,cv=5)

In [66]:
random.fit(x,y)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'max_depth': [5, 10, 15, 20, 30],
                                        'n_estimators': [10, 30, 50, 70, 100,
                                                         150],
                                        'random_state': [0, 1, 2, 3, 4]})

In [67]:
random.best_params_

{'random_state': 0, 'n_estimators': 70, 'max_depth': 30}

In [68]:
random.best_score_

0.9875